name: drupal7.benchmark
recipe: drupal7
config:
  webroot: web
  php: '7.4'
  via: nginx
  database: mariadb:10.2
  composer_version: '1.10.24'
  xdebug: false
tooling:
  drush:
    service: appserver
    cmd:
      - "drush --root=/app/web --uri=http://drupal7.benchmark.lndo.site"
